
project_id = "hjsptwfpbdewwnnrqdlo"
[api]
enabled = true
port = 54321
schemas = ["public", "storage", "auth"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:5173"

[storage]
enabled = true

[functions]
enabled = true

[functions.send-application-email]
verify_jwt = true
