
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjsptwfpbdewwnnrqdlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhqc3B0d2ZwYmRld3dubnJxZGxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NDUxNTQsImV4cCI6MjA1OTMyMTE1NH0.MKi1dGuqwMNtnoAUnSfGkXN9ZHqZagqtZOBTCc3HI7c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
